### ISSUE TITLE
Setup showcase in docker

### ISSUE THREAD

**Issue by ErickKramer** [NoOPeEKS/DataNvim#3]
Hi, 
Thank you for taking the time to prepare a configuration to work with Neovim and Jupyter notebooks. I am very looking forward to finally get a working setup to get jupyter notebooks working with Neovim.

It would be great to have a showcase of the setup in a reproducible environment such as Docker. This could guide users into how to better configure everything. I did that to validate and assert that the neovim configuration I developed to work with [ROS](https://github.com/ErickKramer/ros2-with-neovim) always work as I intended to 

The motivation for this request is that I tried out your instructions in your README and the plugins configurations, but I did not manage to get them working. I mainly had issues with luarocks and magick.

Also, when I ran the `:UpdateRemotePlugins` it failed.

From the instructions, it was not clear to me whether this command `python -m ipykernel --user --name project_name` needs to be run in a separate terminal everytime you want to work with jupyter notebooks.

**Comment by NoOPeEKS** [comment]
Hi @ErickKramer!
Thank you for posting this issue and helping me with your feedback. That is a really good idea, I will most definetely build a showcase in a Docker container as soon as I am freed from final exams!

As for your issues when installing DataNvim, could you please explain in detail what errors and problems you had  when installing luarocks and  magick? Have you installed imagemagick in your system?
Molten.nvim heavily depends on image.nvim which depends itself on the magick rock, so `:UpdateRemotePlugins` is most likely to fail if those plugins could not install correctly.
And sorry, the command `python -m ipykernel --user --name project_name` needs to be run only once your project's virtual environment, if you have one so that molten.nvim can recognize it, which means you have to install pip's ipykernel package previously to your virtual environment before running it.

**Comment by ErickKramer** [comment]
Moreless I manage to recreate my setup with the following Dockerfile using your whole Neovim config instead of mine.

```dockerfile
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG NEOVIM_VERSION=v0.10.0
ARG NODEJS_VERSION=18.18.2

RUN apt-get update \
  && apt-get install -y \
  clang \
  clang-tidy \
  clang-format \
  cmake \
  curl \
  gdb \
  git \
  gettext \
  lua5.1 \
  luarocks \
  ninja-build \
  nodejs \
  npm \
  python3-pip \
  python3-venv \
  ripgrep \
  unzip \
  wget

RUN pip3 install \
  debugpy \
  pynvim \
  ruff \
  uv

# Setup User
RUN groupadd --gid ${USER_GID} ${USERNAME} \
  && useradd -s /bin/bash --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} \
  && apt-get install -y sudo \
  && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME}\
  && chmod 0440 /etc/sudoers.d/${USERNAME} \
  && echo "source /usr/share/bash-completion/completions/git" >> /home/${USERNAME}/.bashrc


USER ${USERNAME}

WORKDIR /home/${USERNAME}

RUN \
  wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.45/quarto-1.5.45-linux-amd64.deb  \
  && sudo apt-get install -y ./quarto-1.5.45-linux-amd64.deb

RUN luarocks --local --lua-version=5.1 install magick

ENV PATH=${PATH}:/home/${USERNAME}/.local/bin

RUN \
  mkdir ~/.virtualenvs \
  && cd ~/.virtualenvs \
  && uv venv neovim

RUN \
  bash -c "source ~/.virtualenvs/neovim/bin/activate && uv pip install ipykernel pynvim jupyter_client cairosvg plotly kaleido pyperclip nbformat pillow && deactivate"

RUN \
  mkdir -p ~/.config/nvim \
  && git clone https://github.com/NoOPeEKS/DataNvim.git ~/.config/nvim

RUN wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash \
  && bash -c ". ${HOME}/.nvm/nvm.sh && nvm install v${NODEJS_VERSION} && nvm use ${NODEJS_VERSION}"

RUN \
  mkdir ~/neovim \
  && git clone https://github.com/neovim/neovim ~/neovim -b "${NEOVIM_VERSION}" \
  && cd ~/neovim \
  && make CMAKE_BUILD_TYE=RelWithDebInfo \
  && sudo make install

RUN nvim --headless "+Lazy! sync" +qa

# Clean up apt cache
RUN sudo apt-get autoremove -y \
  && sudo apt-get clean -y \
  && sudo rm -rf /var/lib/apt/lists/*
```


If you build it and launch neovim you will see the error I am getting

![image](https://github.com/NoOPeEKS/DataNvim/assets/14210967/078c0095-d56a-48be-b081-b1aaaa5ce7d1)

**Comment by ErickKramer** [comment]
On a separate note, I could definitely recommend you to introduce [ruff](https://github.com/astral-sh/ruff) into your setup to replace your python linters.

And [conform.nvim](https://github.com/stevearc/conform.nvim) to improve the formatting experience.

**Comment by NoOPeEKS** [comment]
I seem to have found and solved your problem. The magick rock depends on having imagemagick installed on the system, so if its package is not installed it won't work. Also, I've found that I need to add to the README some extra commands for it to work as it should, because if they aren't run the python kernel can't be loaded due to a bug with ipykernel.

Anyways, please try my modified Dockerfile and see if it works:
```dockerfile
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG NEOVIM_VERSION=v0.10.0

RUN apt-get update -yqq \
  && apt-get install -y \
  clang \
  make \
  build-essential \
  automake \
  clang-tidy \
  clang-format \
  cmake \
  curl \
  gdb \
  git \
  gettext \
  lua5.1 \
  luarocks \
  ninja-build \
  python3-pip \
  python3-venv \
  ripgrep \
  unzip \
  wget \
  libmagickwand-dev \
  imagemagick

RUN pip3 install \
  debugpy \
  pynvim \
  ruff \
  jupytext \
  ipykernel \
  uv

# Setup User
RUN groupadd --gid ${USER_GID} ${USERNAME} \
  && useradd -s /bin/bash --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} \
  && apt-get install -y sudo \
  && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME}\
  && chmod 0440 /etc/sudoers.d/${USERNAME} \
  && echo "source /usr/share/bash-completion/completions/git" >> /home/${USERNAME}/.bashrc


USER ${USERNAME}

WORKDIR /home/${USERNAME}

RUN \
  wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.45/quarto-1.5.45-linux-amd64.deb  \
  && sudo apt-get install -y ./quarto-1.5.45-linux-amd64.deb

RUN luarocks --local --lua-version=5.1 install magick

ENV PATH=${PATH}:/home/${USERNAME}/.local/bin

RUN \
  mkdir ~/.virtualenvs \
  && cd ~/.virtualenvs \
  && uv venv neovim

RUN \
  bash -c "source ~/.virtualenvs/neovim/bin/activate && uv pip install ipykernel jupytext pynvim jupyter_client cairosvg plotly kaleido pyperclip nbformat pillow && deactivate"

RUN \
  mkdir -p ~/.config/nvim \
  && git clone https://github.com/NoOPeEKS/DataNvim.git ~/.config/nvim

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash

ENV NVM_DIR /home/user/.nvm
ENV NODE_VERSION 22.2.0 
RUN bash -c ". $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm alias default $NODE_VERSION"
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN \
  mkdir ~/neovim \
  && git clone https://github.com/neovim/neovim ~/neovim -b "${NEOVIM_VERSION}" \
  && cd ~/neovim \
  && make CMAKE_BUILD_TYPE=RelWithDebInfo \
  && sudo make install

RUN pip install ipykernel \
  && python3 -m ipykernel install --user \
  && sudo ipython kernel install

RUN python3 -m ipykernel & sleep 3 && pkill -f 'python3 -m ipykernel'

RUN nvim --headless "+Lazy! sync" +qa
RUN nvim --headless "+UpdateRemotePlugins" +qa
RUN wget "https://raw.githubusercontent.com/jxareas/Machine-Learning-Notebooks/master/1_Supervised_Machine_Learning/Week%201.%20Introduction%20to%20Machine%20Learning/C1_W1_Lab01_Python_Jupyter_Soln.ipynb"

# Clean up apt cache
RUN sudo apt-get autoremove -y \
  && sudo apt-get clean -y \
  && sudo rm -rf /var/lib/apt/lists/*
```
Build it and run it like this (there is one demo .ipynb in $HOME):
```bash
sudo docker run -it data-nvim /bin/bash
# And once inside container execute nvim
nvim
```

**Comment by NoOPeEKS** [comment]
The image is now available with `docker pull ghcr.io/noopeeks/data-nvim:latest`!
As for your suggestions with Ruff and Comfort, I will try surely try them out!
Thank you for your patience :)
