### ISSUE TITLE
Docker image pull denied

### ISSUE THREAD

**Issue by BoGGoG** [NoOPeEKS/DataNvim#4]
Hi there,
thanks, this looks awesome and like exactly what I've wanted for some time now.

I haven't used docker before, so this might very well be my problem, but I did the following (tried on Fedora 39 and Pop!Os):
- installed docker
- logged in with Github `docker login ghcr.io` etc
- tried pulling your image

```
❯ docker image pull ghcr.io/noopeeks/data-nvim:latest
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/images/create?fromImage=ghcr.io%2Fnoopeeks%2Fdata-nvim&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
❯ docker image pull ghcr.io/noopeeks/data-nvim
Using default tag: latest
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/images/create?fromImage=ghcr.io%2Fnoopeeks%2Fdata-nvim&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
```

Not sure if the package is maybe private.

**Comment by NoOPeEKS** [comment]
Hi @BoGGoG 

The logs you provided seem to indicate that the Docker daemon socket has not been initialized or that you haven't got enough permissions to execute docker.

Could you please try to start the docker service with `sudo systemctl start docker` and then execute the docker pull command with sudo privileges?

Let me know if this worked!

**Comment by NoOPeEKS** [comment]
> Hi @BoGGoG 
> 
> The logs you provided seem to indicate that the Docker daemon socket has not been initialized or that you haven't got enough permissions to execute docker.
> 
> Could you please try to start the docker service with `sudo systemctl start docker` and then execute the docker pull command with sudo privileges?
> 
> Let me know if this worked!

Also if you didn't know, the `docker run -it ghcr.io/noopeeks/data-nvim /bin/bash` command should automatically pull the images needed for the container :)

**Comment by BoGGoG** [comment]
Thanks!
However, also didn't work:

```
❯ sudo systemctl start docker
[sudo] password for xxx:
❯ docker pull ghcr.io/noopeeks/data-nvim:latest
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/images/create?fromImage=ghcr.io%2Fnoopeeks%2Fdata-nvim&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
❯ sudo docker pull ghcr.io/noopeeks/data-nvim:latest
Error response from daemon: Head "https://ghcr.io/v2/noopeeks/data-nvim/manifests/latest": unauthorized
```

I also checked that the token I used for the login has `read:packages` access.

**Comment by NoOPeEKS** [comment]
I checked it and yes, of course it was my fault, the package is private by default. I will change it today and will ping you when it's done! Thank you for posting this issue and making me aware of this, I'm still a noob in the open-source world :)

**Comment by NoOPeEKS** [comment]
@BoGGoG I've changed the visibility of the package and it should be public now, thus accessible for pulling. Let me know if it works

**Comment by BoGGoG** [comment]
Works, thanks a lot!
I also don't know what I'm doing :)
Seems like a good project to learn about all of this, though.
